### ISSUE TITLE
Saving versionless files

### ISSUE THREAD

**Issue by EuniceChen1** [listyque/TACTIC-Handler#33]
I am trying to save version and versionless files at the same time to 2 different file paths. Is this supported? Currently every time I save, even after unchecking the update versionless checkbox, it still overwrites the versionless file. Maybe the way I've set it in the TACTIC web browser is wrong, how should I go about doing so to achive what I want?

**Comment by listyque** [comment]
To save versionless it different path you should setup versionless file naming in your project. But if you want to save versionless to different server, I think you can setup python trigger in tactic, and make it copy your versionless to any path you want.
Bug with overwriting versionless is fixed in upcoming updates.
Feel free to post any bugs you found.
